---
apiVersion: v1
kind: Secret
metadata:
  name: blues-man-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus1/blues-man-frontend-gitops
